os: osx
language: node_js
node_js:
  - 'lts/*'

before_install:
  - curl -o- -L https://dot.net/v1/dotnet-install.sh | bash -s --
  - export PATH="$HOME/.dotnet:$PATH"
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

after_success:
  - test $TRAVIS_BRANCH = "master" && npm i -g codecov
  - test $TRAVIS_BRANCH = "master" && node upload-coverage.js
