branches:
  only:
    - master

max_jobs: 1

install:
  - ps: Install-Product node 13

test_script:
  - node --version
  - npm --version
  - npm install -g yarn
  - yarn
  - node build-travis.js

build: off
